steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clipstream-backend:$SHORT_SHA'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend/'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clipstream-backend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        SHORT_SHA=${SHORT_SHA:-latest}
        gcloud run deploy ${_SERVICE_NAME} \
          --image "gcr.io/$PROJECT_ID/clipstream-backend:$SHORT_SHA" \
          --region "${_REGION}" \
          --platform managed \
          --allow-unauthenticated \
          --port 8080 \
          --env-vars-file=backend/env.yaml \
          --set-secrets="SURREALDB_PASS=surrealdb-password:latest,SECRET_KEY=jwt-secret-key:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,REDIS_PASSWORD=redis-password:latest"

substitutions:
  _SERVICE_NAME: clipstream-backend
  _REGION: us-central1

timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY