
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clipstream-backend:$SHORT_SHA'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend/'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clipstream-backend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        SHORT_SHA=${SHORT_SHA:-latest}
        gcloud run deploy "${_SERVICE_NAME}" \
          --image "gcr.io/$PROJECT_ID/clipstream-backend:$SHORT_SHA" \
          --region "${_REGION}" \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="SURREALDB_URL=wss://ancient-valley-06cu6ilhgptbp4ttr1a04b77oc.aws-euw1.surreal.cloud,SURREALDB_USER=backend,SURREALDB_PASS=YourStrongPassword123,SURREALDB_NS=clipstream,SURREALDB_DB=production,REDIS_URL=redis://:globaldb123@34.182.72.40:6379/0,CELERY_BROKER_URL=redis://:globaldb123@34.182.72.40:6379/0,CELERY_RESULT_BACKEND=redis://:globaldb123@34.182.72.40:6379/1,SECRET_KEY=hOvZRapnpVkdzNIRARCGpitm2q29_8obHDZRNo0wpxY,JWT_ALGORITHM=HS256,ACCESS_TOKEN_EXPIRE_MINUTES=30,GOOGLE_CLIENT_ID=235194927143-j2i2l1v0uf80rddpsd7qucejn3roo31a.apps.googleusercontent.com,GOOGLE_CLIENT_SECRET=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,GOOGLE_REDIRECT_URI=https://clipstream-backend.finailabz.com/api/v1/auth/social/google/callback"


timeout: "1200s"
