"""
Initial Video Dataset

Example production video sources for Clipstream ingestion.
Replace these with your actual video sources (TikTok URLs, CDN URLs, etc.)
"""

# Real playable video URLs from Google's public CDN (works in browsers immediately!)
PRODUCTION_VIDEOS = [
    # Sports
    {
        "url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "category": "sports",
        "duration": 596.5,
        "title": "Basketball Highlights",
        "tags": ["sports", "basketball", "highlights"],
        "creator_id": "user:system",
        "embedding": [],  # Will be generated by ML model
    },
    {
        "url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "category": "sports",
        "duration": 653.8,
        "title": "Soccer Goals Compilation",
        "tags": ["sports", "soccer", "goals"],
        "creator_id": "user:system",
        "embedding": [],
    },
    # Comedy
    {
        "url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "category": "comedy",
        "duration": 15.0,
        "title": "Funny Animals",
        "tags": ["comedy", "animals", "funny"],
        "creator_id": "user:system",
        "embedding": [],
    },
    {
        "url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        "category": "comedy",
        "duration": 15.0,
        "title": "Epic Fails",
        "tags": ["comedy", "fails", "viral"],
        "creator_id": "user:system",
        "embedding": [],
    },
    # Music
    {
        "url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
        "category": "music",
        "duration": 60.0,
        "title": "Guitar Solo",
        "tags": ["music", "guitar", "rock"],
        "creator_id": "user:system",
        "embedding": [],
    },
    {
        "url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
        "category": "music",
        "duration": 15.0,
        "title": "Dance Performance",
        "tags": ["music", "dance", "performance"],
        "creator_id": "user:system",
        "embedding": [],
    },
    # Gaming
    {
        "url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
        "category": "gaming",
        "duration": 15.0,
        "title": "Gaming Highlights",
        "tags": ["gaming", "highlights", "esports"],
        "creator_id": "user:system",
        "embedding": [],
    },
    {
        "url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "category": "gaming",
        "duration": 888.0,
        "title": "Speedrun Record",
        "tags": ["gaming", "speedrun", "record"],
        "creator_id": "user:system",
        "embedding": [],
    },
    # Education
    {
        "url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
        "category": "education",
        "duration": 30.0,
        "title": "How Things Work",
        "tags": ["education", "learning", "science"],
        "creator_id": "user:system",
        "embedding": [],
    },
    {
        "url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "category": "education",
        "duration": 734.0,
        "title": "Quick Science Fact",
        "tags": ["education", "science", "facts"],
        "creator_id": "user:system",
        "embedding": [],
    },
    # Food
    {
        "url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
        "category": "food",
        "duration": 20.0,
        "title": "Quick Recipe",
        "tags": ["food", "recipe", "cooking"],
        "creator_id": "user:system",
        "embedding": [],
    },
    {
        "url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
        "category": "food",
        "duration": 25.0,
        "title": "Food Review",
        "tags": ["food", "review", "restaurant"],
        "creator_id": "user:system",
        "embedding": [],
    },
    # Travel
    {
        "url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
        "category": "travel",
        "duration": 30.0,
        "title": "Travel Vlog",
        "tags": ["travel", "vlog", "adventure"],
        "creator_id": "user:system",
        "embedding": [],
    },
]


# Example: TikTok video URLs to scrape and download
TIKTOK_VIDEO_URLS = [
    "https://www.tiktok.com/@user/video/1234567890",
    "https://www.tiktok.com/@user/video/0987654321",
    # Add more TikTok URLs here
]


# Example: YouTube Shorts URLs
YOUTUBE_SHORTS_URLS = [
    "https://youtube.com/shorts/abc123",
    "https://youtube.com/shorts/xyz789",
    # Add more YouTube Shorts URLs here
]


# Example: Local video files (for testing)
LOCAL_VIDEO_FILES = [
    "/app/uploads/test_video_001.mp4",
    "/app/uploads/test_video_002.mp4",
    # Add more local file paths here
]


# Example: S3/GCS bucket paths
CLOUD_STORAGE_VIDEOS = [
    "gs://clipstream-videos/uploads/video_001.mp4",
    "gs://clipstream-videos/uploads/video_002.mp4",
    # Add more cloud storage paths here
]


def get_initial_videos(source: str = "production"):
    """
    Get initial video dataset based on source type.

    Args:
        source: One of "production", "tiktok", "youtube", "local", "cloud"

    Returns:
        list: Video source data
    """
    sources = {
        "production": PRODUCTION_VIDEOS,
        "tiktok": TIKTOK_VIDEO_URLS,
        "youtube": YOUTUBE_SHORTS_URLS,
        "local": LOCAL_VIDEO_FILES,
        "cloud": CLOUD_STORAGE_VIDEOS,
    }

    return sources.get(source, PRODUCTION_VIDEOS)
