"""
Initial Video Dataset

Example production video sources for Clipstream ingestion.
Replace these with your actual video sources (TikTok URLs, CDN URLs, etc.)
"""

# Example: Real video URLs from your CDN
PRODUCTION_VIDEOS = [
    {
        "url": "https://cdn.finailabz.com/videos/sports/basketball_dunk_001.mp4",
        "category": "sports",
        "duration": 12.4,
        "title": "Amazing Basketball Dunk",
        "tags": ["sports", "basketball", "dunk"],
        "creator_id": "user:system",
        "embedding": [],  # Will be generated by ML model
    },
    {
        "url": "https://cdn.finailabz.com/videos/comedy/funny_cat_002.mp4",
        "category": "comedy",
        "duration": 8.1,
        "title": "Hilarious Cat Fails",
        "tags": ["comedy", "cats", "funny"],
        "creator_id": "user:system",
        "embedding": [],
    },
    {
        "url": "https://cdn.finailabz.com/videos/music/guitar_solo_003.mp4",
        "category": "music",
        "duration": 15.7,
        "title": "Epic Guitar Solo",
        "tags": ["music", "guitar", "rock"],
        "creator_id": "user:system",
        "embedding": [],
    },
    {
        "url": "https://cdn.finailabz.com/videos/gaming/gameplay_004.mp4",
        "category": "gaming",
        "duration": 18.3,
        "title": "Insane Gaming Highlights",
        "tags": ["gaming", "esports", "highlights"],
        "creator_id": "user:system",
        "embedding": [],
    },
    {
        "url": "https://cdn.finailabz.com/videos/food/recipe_005.mp4",
        "category": "food",
        "duration": 22.5,
        "title": "Quick Pasta Recipe",
        "tags": ["food", "recipe", "cooking"],
        "creator_id": "user:system",
        "embedding": [],
    },
]


# Example: TikTok video URLs to scrape and download
TIKTOK_VIDEO_URLS = [
    "https://www.tiktok.com/@user/video/1234567890",
    "https://www.tiktok.com/@user/video/0987654321",
    # Add more TikTok URLs here
]


# Example: YouTube Shorts URLs
YOUTUBE_SHORTS_URLS = [
    "https://youtube.com/shorts/abc123",
    "https://youtube.com/shorts/xyz789",
    # Add more YouTube Shorts URLs here
]


# Example: Local video files (for testing)
LOCAL_VIDEO_FILES = [
    "/app/uploads/test_video_001.mp4",
    "/app/uploads/test_video_002.mp4",
    # Add more local file paths here
]


# Example: S3/GCS bucket paths
CLOUD_STORAGE_VIDEOS = [
    "gs://clipstream-videos/uploads/video_001.mp4",
    "gs://clipstream-videos/uploads/video_002.mp4",
    # Add more cloud storage paths here
]


def get_initial_videos(source: str = "production"):
    """
    Get initial video dataset based on source type.

    Args:
        source: One of "production", "tiktok", "youtube", "local", "cloud"

    Returns:
        list: Video source data
    """
    sources = {
        "production": PRODUCTION_VIDEOS,
        "tiktok": TIKTOK_VIDEO_URLS,
        "youtube": YOUTUBE_SHORTS_URLS,
        "local": LOCAL_VIDEO_FILES,
        "cloud": CLOUD_STORAGE_VIDEOS,
    }

    return sources.get(source, PRODUCTION_VIDEOS)
